# Generated by Django 5.0.14 on 2026-09-03 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_spice_level_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='სახელი და გვარი')),
                ('phone', models.CharField(max_length=30, verbose_name='ტელეფონი')),
                ('address', models.CharField(max_length=255, verbose_name='მისამართი')),
                ('note', models.TextField(blank=True, verbose_name='შენიშვნა')),
                ('status', models.CharField(choices=[('pending', 'მიღებულია'), ('preparing', 'მზადდება'), ('on_the_way', 'გზაშია'), ('delivered', 'ჩაბარებულია'), ('cancelled', 'გაუქმებულია')], default='pending', max_length=20, verbose_name='სტატუსი')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ჯამი')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის დრო')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების დრო')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'შეკვეთა',
                'verbose_name_plural': 'შეკვეთები',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150, verbose_name='კერძი')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ერთეულის ფასი')),
                ('quantity', models.PositiveIntegerField(verbose_name='რაოდენობა')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ჯამი')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.order')),
            ],
            options={
                'verbose_name': 'შეკვეთის კერძი',
                'verbose_name_plural': 'შეკვეთის კერძები',
            },
        ),
    ]
