# Generated by Codex on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'ნაღდი ანგარიშსწორება'), ('card', 'ბარათით გადახდა')], default='cash', max_length=20, verbose_name='გადახდის მეთოდი'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'გადახდა მოლოდინშია'), ('paid', 'გადახდილია')], default='pending', max_length=20, verbose_name='გადახდის სტატუსი'),
        ),
    ]
